### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by iaroel** [barryvdh/laravel-dompdf#118]
Hi Barrycdh,

Using custom fonts doesn't work.
On my css I have:
```css
@font-face {
  font-family: 'RobotoRegular';
  src: url('{{public_path()}}/fonts/Roboto-Regular.ttf')  format('truetype')
}
body{
  font-family: 'RobotoRegular', sans-serif;
}
```
However fonts not showing.
I've set the show_warnings to true and I get this error:
ErrorException in font_metrics.cls.php line 343:
file_put_contents(/project_diroctory/storage/fonts/d313200373e47929206412e716f10ab0.ttf): failed to open stream: No such file or directory.

Then I've created the fonts folder manually and it start working.
I'm not sure if this is the right way or not.
Any advice?
