### ISSUE TITLE
Font ?????????????

### ISSUE THREAD

**Issue by VardgesK** [barryvdh/laravel-dompdf#433]
In my Pdf fonts return "????? ??????? ??" what can i do

**Comment by keevitaja** [comment]
I have the same issue with russian letters. this is the style i am using:

```css
    @font-face {
        font-family: 'Ubuntu';
        src: {{ resource_path('assets/fonts/ubuntu/ubuntu-regular-webfont.ttf') }} format('truetype');
        font-weight: normal;
        font-style: normal;

    }

    @font-face {
        font-family: 'Ubuntu';
        src: {{ resource_path('assets/fonts/ubuntu/ubuntu-medium-webfont.ttf') }} format('truetype');
        font-weight: bold;
        font-style: normal;

    }

    body {
        font-family: "Ubuntu", sans-serif;
        font-size: 14px;
    }
```
