### ISSUE TITLE
Custom Checkbox doesn't work 

### ISSUE THREAD

**Issue by TolgaKara** [barryvdh/laravel-dompdf#606]
I was trying to create a List of Items. Next to the Items should be the checkbox but the renderer dompdf doesnt understand what I am doing.

`````php
$itemTitle = $itemTitle.'<label class="container">'.$item->title.'<input type="checkbox"><span class="checkmark"></span></label>';
`````

`````css
/* The container */
.container {
  display: block;
  position: relative;
  padding-left: 35px;
  margin-bottom: 12px;
  cursor: pointer;
  font-size: 22px;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* Hide the browser's default checkbox */
.container input {
  position: absolute;
  opacity: 0;
  height: 0;
  width: 0;
}

/* Create a custom checkbox */
.checkmark {
  position: absolute;
  top: 0;
  left: 0;
  height: 20px;
  width: 20px;
  border: 2px solid #cccccc;
  border-radius: 3px;
  background-color: #ffffff;
}
`````

`````php
$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('isJavascriptEnabled', true);
$options->set('isHtml5ParserEnabled', true);

$dompdf	= new Dompdf($options);
$dompdf->loadHtml($content.'</body></html>');
$dompdf->render();

$dompdf->set_base_path(public_path('cssex-pdf.css'));
$dompdf->stream('hello.pdf');
`````

- [ ] Without the DomPDF renderer on the Web

With the Code given and using DomPDF - [ ]

I check if dompdf does not support any of the given css styles but didn't found any which doesnt get supported by dompdf. So like I used [CSSCompatibility](https://github.com/dompdf/dompdf/wiki/CSSCompatibility)

I am really confused it does work without the renderer. Hopefully it get fixed or you guys can help me.
